apiVersion: v1
kind: Namespace
metadata:
  name: {{required "Namespace name must be defined." .Values.name}}
  labels:
    {{- if .Values.isCoreInfra }}
    coreinfra: atmos
    {{- end }}
    {{- include "atmos-namespace.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
